### ISSUE TITLE
Issueではありませんが。。。

### ISSUE THREAD

**Issue by marzenakrp** [neologd/mecab-ipadic-neologd#44] opened 2018-05-08 02:16 UTC
大変申し訳ないですが、本辞書とMECABの既存辞書を一緒に使うのがおすすめと言うことなんですが、両方を使うにはどうすればいいか教えていただけますか。

**Comment by overlast** [comment] 2018-05-08 13:31
Thank you for your question 😁

When using different dictionaries during morphological analysis, you may get different analysis results from a same sentence.
In the world, there are applications of a type that can obtain useful information from the differences.

In order to obtain and utilize the differences, for example, the following three steps are processed.

Step 1.
Make multiple instances of MeCab's Tagger in any programming language.
At that time, you should set a path of different system dictionary with the -d option for each instance.

Step 2.
Get multiple analysis results using each instance.

Step 3.
Implement a process to obtain arbitrary information by utilizing multiple analysis results beforehand. 
And let's get the result of this process.

- Imaginable example
    - Extract only nouns from multiple analysis results, merge them, and create a noun list with frequency

That's all.

**Comment by neologd** [comment] 2018-05-08 13:50
If the problem is resolved, we will close this request 1 week after 😉

**Closed as completed** 2018-05-15 07:46 UTC
